server:
  port: 8100
#  ssl:
#    key-store: classpath:cjbjw.cn.jks # 证书存放的位置
#    key-store-type: JKS # P12证书格式
#    key-store-password: 5njg91io
#    enabled: true

#http-port: 8090 # http重定向https配置

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/translation?&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: Root@159
  devtools:
    restart:
      enabled: true
      exclude: static/**,public/**

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1 # \u903B\u8F91\u5DF2\u5220\u9664\u503C(\u9ED8\u8BA4\u4E3A 1)
      logic-not-delete-value: 0 # \u903B\u8F91\u672A\u5220\u9664\u503C(\u9ED8\u8BA4\u4E3A 0)
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springdoc:
  swagger-ui:
    path: /swagger-ui
